name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: test

    steps:

      - name: Check files
        run: ls -a

      - name: path
        run: pwd  
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files
        run: ls -a

